### ISSUE TITLE
robot model

### ISSUE THREAD

**Issue by gautica** [ZhengyiLuo/PerpetualHumanoidControl#1]
Hi,
Thanks for your great work. It is really interesting to see your results. I want to ask how you sort the hardness of motions. Do you have some program to do it automatically? and also, there are many data in the dataset that are not possible, for example, climbing stairs; how do you filter them out?  is it possible to upload your humanoid robot file (in xml or urdf)? Thank you very much.

**Comment by ZhengyiLuo** [comment]
All will be provided with the code release, stay tuned :)

**Comment by ZhengyiLuo** [comment]
Main training/testing code is now released.
