### ISSUE TITLE
Custom animation input?

### ISSUE THREAD

**Issue by kexul** [ZhengyiLuo/PerpetualHumanoidControl#11]
@ZhengyiLuo May I solicit your guidance for custom animation input? 😳 
I'd like to use animation stored in `.fbx` file as input, which was wildly used in industry.  

I've came up with two ways to do that: 
1. Convert the animation to smpl format and use it as input. Then use the script provided in `data_process` folder: `process_amass_raw.py -> process_amass_db.py -> convert_amass_isaac.py`
2. Dig deeper into `conver_amass_isaac.py`, write code to convert fbx to somthing that can be directly used in isaacgym. 

What's your advice? Many thanks!

**Comment by ZhengyiLuo** [comment]
Go from smpl -> isaac format would probably be the easiest. The real heavy lifting from SMPL to isaac all happens in `conver_amass_isaac.py`, the previous two scripts are just data filtering and aggregating (probably should have just  used one script). 

The simulation result can also be converted back to SMPL (for rendering mesh) in real time.
