### ISSUE TITLE
How to evaluate with only kepoints data?

### ISSUE THREAD

**Issue by Cr7st** [ZhengyiLuo/PerpetualHumanoidControl#13]
Thanks for your execellent work! However, I have encountered some problems when trying to run the code.

I've noticed that you provided a command to run evaluation with only keypoints:
```
## keypoint model
python phc/run.py --task HumanoidImMCPGetup --cfg_env phc/data/cfg/phc_kp_mcp_iccv.yaml --cfg_train phc/data/cfg/train/rlg/im_mcp.yaml --motion_file sample_data/amass_isaac_standing_upright_slim.pkl --network_path output/phc_kp_mcp_iccv --test --num_envs 1 --epoch -1  --no_virtual_display
```

But it seems that in the motion_file `amass_isaac_standing_upright_slim.pkl`, there isn't any direct information of joint position. Do you calculate the keypoints from joint rotation? What should I do if I only have joint position?

**Comment by kexul** [comment]
https://github.com/GuyTevet/motion-diffusion-model/issues/5 this might help if you're using MDM generated animation. After getting smpl format data, you can use the process_amass_raw.py -> process_amass_db.py -> convert_amass_isaac.py pipeline I think.

**Comment by Cr7st** [comment]
Thanks! I've tried that but got the robot facing up(z-up) on the ground.
![image](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/assets/73263561/f03ea075-684e-4955-8604-ac1f705b0957)

I tried to use `transform_utils.rotate_smpl_root_and_trans` to rotate it to y-up and the motion messed up totally.
```
pose_aa, root_trans = transform_utils.rotate_smpl_root_and_trans(pose_aa,
                                                                     torch.from_numpy(root_trans),
                                                                     [np.pi / 2, 0, 0])
```
![image](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/assets/73263561/82e56d17-7317-44ba-ade6-61743d952fb6)

**Comment by kexul** [comment]
That's funny 🤣 Sorry that I made things worse...  @ZhengyiLuo may provide more insight. 
Me also struggling to export my fbx to smpl as I posted some days ago https://github.com/ZhengyiLuo/PerpetualHumanoidControl/issues/11, not finding a proper way yet. 

The `image and language-based demo code.`  is listed in todo list of the README, maybe we just need to wait patiently. 😉

**Comment by ZhengyiLuo** [comment]
Here is the [script](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/master/scripts/data_process/convert_data_mdm.py) I use for converting from **dumped** mdm data to the format I need. 

Two conversions you will need is:
```
transform = sRot.from_euler('xyz', np.array([np.pi / 2, 0, 0]), degrees=False)
    new_root = (transform * sRot.from_rotvec(pose_aa[:, :3])).as_rotvec()
    pose_aa[:, :3] = new_root
```
which rotates the root to make it with a "z-up" coordinate system. 

Then 
```
pose_quat_global = (sRot.from_quat(new_sk_state.global_rotation.reshape(-1, 4).numpy()) * sRot.from_quat([0.5, 0.5, 0.5, 0.5]).inv()).as_quat().reshape(B, -1, 4)  # should fix pose_quat as well here...
```

, which transforms the SMPL coordinate system to the ones used in "up_right_start". 

If no rotation is needed, just joints, please refer to the [file](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/d1ca8014b536832976cff2586c98b5474773ecfa/phc/env/tasks/humanoid_im_mcp_demo.py#L253), which is all the simulation-side code I use for doing the mdm & real-time demo.

**Comment by ZhengyiLuo** [comment]
And you are right about the joint position; I do not store joint positions in the file but only joint rotations, and perform forward-kinematics on the fly. 

The walkaround for this issue is embbed in the "real_traj" flag, which bypass this issue and directly set joint positions. It is a little hacky but gets the job done. If you want to dig deeper into this (before I get around to write more about it), you can do a global search on "real_traj" to see how it is done.

**Comment by ZhengyiLuo** [comment]
> [GuyTevet/motion-diffusion-model#5](https://github.com/GuyTevet/motion-diffusion-model/issues/5) this might help if you're using MDM generated animation. After getting smpl format data, you can use the process_amass_raw.py -> process_amass_db.py -> convert_amass_isaac.py pipeline I think.

only convert_amass_isaac.py is needed :)

**Comment by Cr7st** [comment]
> Here is the [script](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/master/scripts/data_process/convert_data_mdm.py) I use for converting from **dumped** mdm data to the format I need.
> 
> Two conversions you will need is:
> 
> ```
> transform = sRot.from_euler('xyz', np.array([np.pi / 2, 0, 0]), degrees=False)
>     new_root = (transform * sRot.from_rotvec(pose_aa[:, :3])).as_rotvec()
>     pose_aa[:, :3] = new_root
> ```
> 
> which rotates the root to make it with a "z-up" coordinate system.
> 
> Then
> 
> ```
> pose_quat_global = (sRot.from_quat(new_sk_state.global_rotation.reshape(-1, 4).numpy()) * sRot.from_quat([0.5, 0.5, 0.5, 0.5]).inv()).as_quat().reshape(B, -1, 4)  # should fix pose_quat as well here...
> ```
> 
> , which transforms the SMPL coordinate system to the ones used in "up_right_start".
> 
> If no rotation is needed, just joints, please refer to the [file](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/d1ca8014b536832976cff2586c98b5474773ecfa/phc/env/tasks/humanoid_im_mcp_demo.py#L253), which is all the simulation-side code I use for doing the mdm & real-time demo.

Thanks a lot for helping out! Just found out that my `pose_aa` was of shape (B * 24, 3) since it was transformed from rot6d (). I reshaped it to (B, 72) and it worked.

By the way, I‘m wondering if there are any plans to release a demo script in the future that directly takes keypoints as input, similar to how the current script handles rotations. I noticed that "Release image and language-based demo code." is on your to-do list. Really looking forward to it.

**Comment by ZhengyiLuo** [comment]
Video demo script now released on master.
