### ISSUE TITLE
Where is the training code?

### ISSUE THREAD

**Issue by phj128** [ZhengyiLuo/PerpetualHumanoidControl#2]
Hi, thanks for your great work.
Although README gives instructions for running code and says the training code is released, I cannot find the code. 
When will you release the training code?

**Comment by ZhengyiLuo** [comment]
Hi! 

Thanks a ton for your interest in my work.

Everything is ready to go on my end but I still awaiting some responses about license & IP usage, which is taking a lot longer than I expected. I will push the code once they are cleared up :).

**Comment by ZhengyiLuo** [comment]
Main training/testing code is now released.
