### ISSUE TITLE
Miss library

### ISSUE THREAD

**Issue by huey0528** [ZhengyiLuo/PerpetualHumanoidControl#20]
I notice the convert_data_mdm.py missed two libraries which are uhc.utils.config_utils.copycat_config and uhc.smpllib.smpl_robot. Have anyone try the convert_data_mdm.py file?

**Comment by ZhengyiLuo** [comment]
Those libraries aren't used I think; you can just comment them out.

That being said this file is meant more as an example instead of directly runnable:) 

Language demo is still a work in progress since MDM is a little slow. I will have a working version here soon

**Comment by huey0528** [comment]
Got it, thank you for your help ~
