### ISSUE TITLE
How to get the simulation result file

### ISSUE THREAD

**Issue by Sparkle6979** [ZhengyiLuo/PerpetualHumanoidControl#21]
Thanks for your amazing work.
What should I do if I want to get the results of the simulation from Issac gym, such as a file of key points or SMPL parameters?

**Comment by OoSnowfxm** [comment]
I have the same question

**Comment by ZhengyiLuo** [comment]
Press L to start recording video and state, and press L again to end recording and dump states. 

The recording will record both a video file and simulation state file. To convert the simulation state file, refer to this (script)[https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/master/scripts/render_smpl_o3d.py]. I will push another one that shows an interactive viewport.
