### ISSUE TITLE
Evaluate with only keypoints when num_envs>1

### ISSUE THREAD

**Issue by yw0208** [ZhengyiLuo/PerpetualHumanoidControl#24]
Hi, excellent work!
I'm trying to achieve evaluating with only keypoints based on [humanoid_im_mcp_demo](https://github.com/ZhengyiLuo/PerpetualHumanoidControl/blob/05560913acc9c6215b3b2e884b562aac7663cdfc/phc/env/tasks/humanoid_im_mcp_demo.py).
But it seems like it can only imitate one motion at a time. Would you happen to have any suggestions for imitating multiple motions simultaneously?
I would appreciate it if you could reply.

**Comment by ZhengyiLuo** [comment]
Should be pretty easy; in this demo code I am feeding one keypoint to the environment, and all you need to do for multiple people is creating two humanoids (env.num_envs=2) and then feed different keypoints for them to track.
