### ISSUE TITLE
Details about the data

### ISSUE THREAD

**Issue by hartikainen** [ZhengyiLuo/PerpetualHumanoidControl#5]
Hey folks,

Thanks for the open-source release. I played around with the repo and noticed a small differences between the data numbers resulting from the [preprocessing scripts](https://github.com/ZhengyiLuo/PerpetualHumanoidControl?tab=readme-ov-file#training) and the paper/readme. I get 11315 training and 138 test samples, compared to your reported 11313 training and 140 test samples.

My questions are:
1) Am I correct that you're using the `SMPL+H G`-files (as opposed to `SMPL-X G`) from the [AMASS website](https://amass.is.tue.mpg.de/download.php)?
2) Would it be possible to upload the list of AMASS ids for train/test/validation splits somewhere?

**Comment by ZhengyiLuo** [comment]
1. Yes, I am. 
2. This is my bad, there are two straggling sequence that I meant to remove "'0-ACCAD_Female1General_c3d_A12 - crawl backwards_poses', '0-ACCAD_Female1General_c3d_A11 - crawl forward_poses'". The crawling sequence has a decent amount of ground penetration so I removed them; I think these two aren't THAT bad so keeping them should also be fine in general. For consistency (11313 sequences) I kept them removed. As for testing, there are also two sequences with similar ground penetration issues that I removed (resulting in 138 sequences, out of the original 140). I didn't do this for PHC but for PULSE I added it. For more information about this process, please refer to [PULSE](http://zhengyiluo.github.io/PULSE)'s supplementary materials. 

I have updated the amass_occlusion_v3 file, which you can download the newer version by reruning the download script. Using that should give you the same IDs/sequences I use.
