### ISSUE TITLE
Evaluation on AMASS

### ISSUE THREAD

**Issue by sujeet-gandhi** [ZhengyiLuo/PerpetualHumanoidControl#9]
Hi,
Thanks for your work.
I am getting the below error while running the evaluation code on AMASS:
>
Traceback (most recent call last):
  File "phc/run.py", line 297, in <module>
    main()
  File "phc/run.py", line 288, in main
    runner = build_alg_runner(algo_observer)
  File "phc/run.py", line 203, in build_alg_runner
    runner.model_builder.model_factory.register_builder('amp', lambda network, **kwargs: amp_models.ModelAMPContinuous(network))
AttributeError: 'Runner' object has no attribute 'model_builder'
>

Additionally, could you please also verify once the versions of: isaacgym, rlgames and pytorch?

Thanks

**Comment by ZhengyiLuo** [comment]
Please refer to the [dependencies section](https://github.com/ZhengyiLuo/PerpetualHumanoidControl#dependencies). 

In short, newest isaacgym and pytorch (though I am using 1.12.1) should work. Newest IsaacGym (preview 4) and rlgames 1.1.4 (as in requirements.txt).
